import config from '@config/index';

export const OTP_EXPIRY_MINUTES = config.OTP_EXPIRY_MINUTES;
export const ACCESS_TOKEN_EXPIRATION = config.ACCESS_TOKEN_EXPIRATION;
export const REFRESH_TOKEN_EXPIRATION = config.REFRESH_TOKEN_EXPIRATION;
export const PLATFORM_COMMISSION_PERCENTAGE = config.PLATFORM_COMMISSION_PERCENTAGE;